# Global settings applied to the whole site.
[build]
  # Directory to publish (build output directory).
  publish = "build/"
  
  # Build command.
  command = "npm run build"

# Redirects and rewrite rules for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  