name: Install & Build Vite App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          registry-url: https://npm.pkg.github.com/
          scope: "@integritymarketing"

      - name: Set up .npmrc for GitHub Packages
        run: |
          echo "@integritymarketing:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build Vite app
        run: yarn build
